# Generated by Django 4.2.7 on 2023-11-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='ethereum_address',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
